/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskPredictionRouteImport } from './routes/risk-prediction'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperationsIndexRouteImport } from './routes/operations.index'
import { Route as OperationsSettingsRouteImport } from './routes/operations.settings'
import { Route as OperationsPredictiveRouteImport } from './routes/operations.predictive'
import { Route as OperationsLifecycleRouteImport } from './routes/operations.lifecycle'
import { Route as OperationsIncidentsRouteImport } from './routes/operations.incidents'
import { Route as OperationsDevicesRouteImport } from './routes/operations.devices'
import { Route as OperationsDecisionsRouteImport } from './routes/operations.decisions'
import { Route as OperationsComplianceRouteImport } from './routes/operations.compliance'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskPredictionRoute = RiskPredictionRouteImport.update({
  id: '/risk-prediction',
  path: '/risk-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsIndexRoute = OperationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsSettingsRoute = OperationsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsPredictiveRoute = OperationsPredictiveRouteImport.update({
  id: '/predictive',
  path: '/predictive',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsLifecycleRoute = OperationsLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsIncidentsRoute = OperationsIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsDevicesRoute = OperationsDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsDecisionsRoute = OperationsDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => OperationsRoute,
} as any)
const OperationsComplianceRoute = OperationsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => OperationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/executive': typeof ExecutiveRoute
  '/operations': typeof OperationsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/risk-prediction': typeof RiskPredictionRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/decisions': typeof OperationsDecisionsRoute
  '/operations/devices': typeof OperationsDevicesRoute
  '/operations/incidents': typeof OperationsIncidentsRoute
  '/operations/lifecycle': typeof OperationsLifecycleRoute
  '/operations/predictive': typeof OperationsPredictiveRoute
  '/operations/settings': typeof OperationsSettingsRoute
  '/operations/': typeof OperationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/executive': typeof ExecutiveRoute
  '/reports': typeof ReportsRoute
  '/risk-prediction': typeof RiskPredictionRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/decisions': typeof OperationsDecisionsRoute
  '/operations/devices': typeof OperationsDevicesRoute
  '/operations/incidents': typeof OperationsIncidentsRoute
  '/operations/lifecycle': typeof OperationsLifecycleRoute
  '/operations/predictive': typeof OperationsPredictiveRoute
  '/operations/settings': typeof OperationsSettingsRoute
  '/operations': typeof OperationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/decisions': typeof DecisionsRoute
  '/executive': typeof ExecutiveRoute
  '/operations': typeof OperationsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/risk-prediction': typeof RiskPredictionRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/operations/compliance': typeof OperationsComplianceRoute
  '/operations/decisions': typeof OperationsDecisionsRoute
  '/operations/devices': typeof OperationsDevicesRoute
  '/operations/incidents': typeof OperationsIncidentsRoute
  '/operations/lifecycle': typeof OperationsLifecycleRoute
  '/operations/predictive': typeof OperationsPredictiveRoute
  '/operations/settings': typeof OperationsSettingsRoute
  '/operations/': typeof OperationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/compliance'
    | '/copilot'
    | '/dashboard'
    | '/decisions'
    | '/executive'
    | '/operations'
    | '/reports'
    | '/risk-prediction'
    | '/settings'
    | '/simulator'
    | '/operations/compliance'
    | '/operations/decisions'
    | '/operations/devices'
    | '/operations/incidents'
    | '/operations/lifecycle'
    | '/operations/predictive'
    | '/operations/settings'
    | '/operations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/compliance'
    | '/copilot'
    | '/dashboard'
    | '/decisions'
    | '/executive'
    | '/reports'
    | '/risk-prediction'
    | '/settings'
    | '/simulator'
    | '/operations/compliance'
    | '/operations/decisions'
    | '/operations/devices'
    | '/operations/incidents'
    | '/operations/lifecycle'
    | '/operations/predictive'
    | '/operations/settings'
    | '/operations'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/compliance'
    | '/copilot'
    | '/dashboard'
    | '/decisions'
    | '/executive'
    | '/operations'
    | '/reports'
    | '/risk-prediction'
    | '/settings'
    | '/simulator'
    | '/operations/compliance'
    | '/operations/decisions'
    | '/operations/devices'
    | '/operations/incidents'
    | '/operations/lifecycle'
    | '/operations/predictive'
    | '/operations/settings'
    | '/operations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DecisionsRoute: typeof DecisionsRoute
  ExecutiveRoute: typeof ExecutiveRoute
  OperationsRoute: typeof OperationsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  RiskPredictionRoute: typeof RiskPredictionRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-prediction': {
      id: '/risk-prediction'
      path: '/risk-prediction'
      fullPath: '/risk-prediction'
      preLoaderRoute: typeof RiskPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/': {
      id: '/operations/'
      path: '/'
      fullPath: '/operations/'
      preLoaderRoute: typeof OperationsIndexRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/settings': {
      id: '/operations/settings'
      path: '/settings'
      fullPath: '/operations/settings'
      preLoaderRoute: typeof OperationsSettingsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/predictive': {
      id: '/operations/predictive'
      path: '/predictive'
      fullPath: '/operations/predictive'
      preLoaderRoute: typeof OperationsPredictiveRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/lifecycle': {
      id: '/operations/lifecycle'
      path: '/lifecycle'
      fullPath: '/operations/lifecycle'
      preLoaderRoute: typeof OperationsLifecycleRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/incidents': {
      id: '/operations/incidents'
      path: '/incidents'
      fullPath: '/operations/incidents'
      preLoaderRoute: typeof OperationsIncidentsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/devices': {
      id: '/operations/devices'
      path: '/devices'
      fullPath: '/operations/devices'
      preLoaderRoute: typeof OperationsDevicesRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/decisions': {
      id: '/operations/decisions'
      path: '/decisions'
      fullPath: '/operations/decisions'
      preLoaderRoute: typeof OperationsDecisionsRouteImport
      parentRoute: typeof OperationsRoute
    }
    '/operations/compliance': {
      id: '/operations/compliance'
      path: '/compliance'
      fullPath: '/operations/compliance'
      preLoaderRoute: typeof OperationsComplianceRouteImport
      parentRoute: typeof OperationsRoute
    }
  }
}

interface OperationsRouteChildren {
  OperationsComplianceRoute: typeof OperationsComplianceRoute
  OperationsDecisionsRoute: typeof OperationsDecisionsRoute
  OperationsDevicesRoute: typeof OperationsDevicesRoute
  OperationsIncidentsRoute: typeof OperationsIncidentsRoute
  OperationsLifecycleRoute: typeof OperationsLifecycleRoute
  OperationsPredictiveRoute: typeof OperationsPredictiveRoute
  OperationsSettingsRoute: typeof OperationsSettingsRoute
  OperationsIndexRoute: typeof OperationsIndexRoute
}

const OperationsRouteChildren: OperationsRouteChildren = {
  OperationsComplianceRoute: OperationsComplianceRoute,
  OperationsDecisionsRoute: OperationsDecisionsRoute,
  OperationsDevicesRoute: OperationsDevicesRoute,
  OperationsIncidentsRoute: OperationsIncidentsRoute,
  OperationsLifecycleRoute: OperationsLifecycleRoute,
  OperationsPredictiveRoute: OperationsPredictiveRoute,
  OperationsSettingsRoute: OperationsSettingsRoute,
  OperationsIndexRoute: OperationsIndexRoute,
}

const OperationsRouteWithChildren = OperationsRoute._addFileChildren(
  OperationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DecisionsRoute: DecisionsRoute,
  ExecutiveRoute: ExecutiveRoute,
  OperationsRoute: OperationsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  RiskPredictionRoute: RiskPredictionRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
