spring.application.name=backend

# AI Configuration
#ai.provider=openrouter
#ai.model=qwen/qwen3-next-80b-a3b-instruct:free
#ai.base-url=https://openrouter.ai/api/v1
#ai.api-key=<OPENROUTER_API_KEY >
#ai.temperature=0.2

ai.provider=groq
ai.base-url=https://api.groq.com/openai/v1
ai.api-key=<GROQ_API_KEY>
ai.model=llama-3.3-70b-versatile
ai.temperature=0.2

# Optional
spring.jackson.serialization.indent_output=true